name: getx_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project
environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter:
    sdk: flutter
  image_picker: ^1.0.4
 
   
dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/fake store logo.png"

flutter:
  uses-material-design: true
  assets: 
    - assets/fake store logo.png
    - assets/item1.png
    - assets/item2.png
    - assets/item3.png
    - assets/item4.png
    - assets/item5.png
    - assets/item6.png
    - assets/formimage.png

  fonts: 
    - family: Poppins
      fonts: 
        - asset: assets/fonts/Poppins-Black.ttf
    - family: Poppins Light
      fonts: 
        - asset: assets/fonts/Poppins-Light.ttf
    - family: Poppins Medium
      fonts: 
        - asset: assets/fonts/Poppins-Medium.ttf
    - family: Poppins Regular
      fonts: 
        - asset: assets/fonts/Poppins-Regular.ttf
    - family: Poppins Bold
      fonts: 
        - asset: assets/fonts/Poppins-Bold.ttf
